In [1]:
import numpy as np
lists = [i for i in range(10)]
new_arr = np.array(lists)
new_arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [2]:
ones_arr = np.ones(10)
ones_arr

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [3]:
zeros_arr = np.zeros(10)
zeros_arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [4]:
arr3 = np.full(shape = [5,6],fill_value=3.14)
arr3

array([[3.14, 3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14, 3.14]])

In [5]:

arr4 = np.arange(start = 0,stop = 20,step = 2)
arr4

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [6]:
arr5 = np.linspace(start=0,stop=15,num=4)
arr5

array([ 0.,  5., 10., 15.])

In [7]:

arr6 = np.random.randint(1,50,size=4)
arr6

array([41, 48, 26, 11], dtype=int32)

In [8]:
arr8 = np.random.random(size=6)
arr8

array([0.03895093, 0.52993999, 0.15317729, 0.51827757, 0.50718969,
       0.83032583])

In [9]:
arr7 = np.random.randn(3)
arr7

array([-0.03380003,  0.01243817,  0.23547583])

In [10]:
arr7 = np.random.randn(3,3)
arr7

array([[-0.09295801,  0.45945184,  0.24528895],
       [ 0.25303285,  1.21119599,  0.41446463],
       [-0.56448256,  1.52380654,  2.8229427 ]])

In [11]:
arr7 = np.random.randn(3,3,3)
arr7

array([[[-1.67309947, -0.29101315,  0.59271351],
        [-1.37556063,  0.58385204,  0.00523805],
        [-0.98537019,  0.31822772,  1.43139654]],

       [[-0.15223919, -0.03213041, -0.51516885],
        [ 0.29074896,  1.66443237, -0.80292933],
        [ 0.12250953,  1.34868055, -1.34739163]],

       [[ 0.31090619,  1.19682653,  0.08041266],
        [ 0.15222634,  0.83248662, -0.17525884],
        [ 3.44203866,  1.32597581, -1.52291819]]])

In [12]:
arr7 = np.random.randn(3,3,3,3)
arr7

array([[[[ 1.54804246, -0.70822584,  0.42264976],
         [-1.22778951,  1.03665312,  1.41960063],
         [ 0.4485593 , -0.195104  , -0.73794719]],

        [[-0.01788417,  0.26660041, -0.29313161],
         [ 1.34369071, -1.47832689,  0.58338551],
         [ 0.1931321 , -0.54215997, -3.00113815]],

        [[-0.97431987, -1.02415717,  0.49912527],
         [-1.47459121, -0.26152519, -0.33682274],
         [-0.61306796, -0.8410058 , -1.26389383]]],


       [[[ 0.1358095 ,  0.25578781,  0.46606273],
         [ 0.49745743, -0.28633519,  0.77074248],
         [-1.21188026, -0.0484452 , -2.17657068]],

        [[-0.09669493, -1.71323728,  0.11015243],
         [-0.56538251,  0.61934346,  0.61907124],
         [ 0.77114252, -1.7462275 , -0.09641491]],

        [[ 0.91526194,  0.05412394,  1.92992314],
         [-0.69059967,  0.80930454,  0.34117318],
         [ 2.35250333,  0.01014234,  1.01306584]]],


       [[[ 0.49548327,  0.82285073, -1.81798038],
         [-0.66107102, -0.39340205

In [13]:
arr = np.array([1,2,3,4,5],dtype = 'float32')
arr

array([1., 2., 3., 4., 5.], dtype=float32)

In [14]:
arr = np.asarray([1,2,3,4,5],dtype = 'float32')
arr

array([1., 2., 3., 4., 5.], dtype=float32)

In [15]:
arr = np.array([1,2,3,4,5],dtype = 'float32')
arr

array([1., 2., 3., 4., 5.], dtype=float32)

In [17]:
arr = np.random.randint(0,100,size = (3,4,5))
arr.ndim

3

In [18]:
arr = np.random.randint(0,100,size = (3,4,5))
arr.shape

(3, 4, 5)

In [19]:
arr = np.random.randint(0,100,size = (3,4,5))
print(arr.dtype)
print(type(arr.dtype))

int32
<class 'numpy.dtypes.Int32DType'>


In [20]:
arr = np.random.randint(0,100,size = (3,4,5))
arr.size

60

In [21]:
arr = np.random.randint(0,100,size = (3,4,5))
arr.itemsize

4

In [22]:
arr = np.random.randint(0,100,size = (3,4,5))
arr.flags
print(type(arr.flags))

<class 'numpy._core.multiarray.flagsobj'>


In [24]:
arr1 = np.random.randint(0,100,size = (2,2))
arr2 = np.random.randint(0,100,size = (2,2))

# 数组间矩阵运算
arr1 + arr2 # 加法
arr1 - arr2 # 减法
arr1 * arr2 # 乘法
arr1 / arr2 # 除法
arr1 ** arr2 # 幂
arr1 // arr2 # 整除
arr1 % arr2 # 取余


array([[ 4, 11],
       [12,  7]], dtype=int32)

In [25]:
# 测试数组创建;
arr1 = np.random.randint(0,100,size = 10)
arr2 = np.random.randint(0,100,size = (8,8))
arr3 = np.random.randint(0,100,size = (8,8,8))



In [26]:
arr1[1:7:2] # 索引1开始，到索引7前一位结束，步长为2
arr1[:] # 没有开头没有结尾，步长默认 - 浅拷贝当前数组对象
arr1[::-1] # 没有开头没有结尾，步长-1 - 一维数组反序

array([91, 41, 42, 38, 44,  4, 89, 69, 24,  7], dtype=int32)

In [27]:
arr2[1:7:2,2:4:1] # 第一维：索引1开始，索引7前一位结束，步长2；第二维：索引2开始，索引4前一位结束，步长1
arr2[:,:] # 第一第二维均没有开头没有结尾，步长默认 - 浅拷贝当前数组对象
arr2[::-1,::-1] # 第一第二维均没有开头没有结尾，步长-1 - 二维数组反序

array([[45, 26, 21, 39, 18, 88,  7,  2],
       [59, 57, 56, 74, 88, 49,  9, 87],
       [12,  3, 71, 66, 56, 49, 56,  8],
       [11, 47, 62, 19, 49,  3, 95,  5],
       [19, 58, 31,  0, 84, 62, 29, 78],
       [54, 94, 87, 74,  0, 32, 30, 78],
       [71, 77, 17, 68, 36,  8, 21, 27],
       [84, 59, 48, 77, 12, 37, 71, 79]], dtype=int32)

In [28]:
arr3[1:7:2,2:4:1,3:8:3] # 第一维：索引1开始，索引7前一位结束，步长2；第二维：索引2开始，索引4前一位结束，步长1；第三维：索引3开始，索引8前一位结束，步长3
arr3[:,:,:] # 第一第二维第三维均没有开头没有结尾，步长默认 - 浅拷贝当前数组对象
arr3[::-1,::-1,::-1] # 第一第二维第三维均没有开头没有结尾，步长-1 - 三维数组反序

array([[[68, 57, 36, 30, 81, 80, 63, 86],
        [75, 32, 43,  1, 23, 31, 37, 10],
        [94, 64, 57, 66, 79,  3, 48, 45],
        [29,  8, 60, 43, 26, 10, 91, 27],
        [ 6, 83, 83,  5, 15, 85, 59, 24],
        [74, 40,  7, 50, 61, 53, 87, 70],
        [27, 46, 77, 38, 71, 11, 42,  4],
        [70, 40, 78, 63, 52, 95, 35, 31]],

       [[41, 96, 45, 51, 69, 21, 29, 26],
        [15, 60,  9, 20, 93,  3, 50, 55],
        [88, 43, 21, 93, 48, 94, 62, 89],
        [34, 68, 21, 97, 90, 89,  7, 38],
        [97, 61, 92, 90, 37, 58, 71, 51],
        [44, 21, 25, 46, 62, 53, 29, 99],
        [70, 40, 90, 17, 20, 59, 22, 80],
        [ 3, 41, 39, 68,  8, 28, 15,  5]],

       [[23, 22, 32, 14, 27, 67, 53, 48],
        [55, 22, 82, 84, 65, 43, 88, 59],
        [29, 58, 44, 61, 55, 21, 55, 27],
        [77, 54, 71, 50, 59, 23, 51, 98],
        [29, 46, 98, 29, 83, 79, 92, 23],
        [64,  3, 84, 99, 48, 79, 53, 50],
        [33, 99, 24,  8, 33, 25, 91, 69],
        [11, 27, 70, 63, 91, 5

In [29]:
# 准备一个三维数组
arr = np.random.randint(0,10,size = (3,4,5))
arr

array([[[3, 8, 6, 5, 7],
        [6, 6, 4, 2, 0],
        [3, 7, 8, 4, 0],
        [7, 5, 7, 7, 3]],

       [[3, 0, 4, 0, 7],
        [8, 9, 1, 4, 8],
        [1, 5, 7, 2, 5],
        [8, 2, 9, 5, 7]],

       [[7, 5, 5, 9, 2],
        [1, 6, 8, 2, 0],
        [3, 5, 6, 0, 3],
        [8, 2, 0, 4, 6]]], dtype=int32)

In [30]:
arr2 = arr.reshape((12,5))
arr2

array([[3, 8, 6, 5, 7],
       [6, 6, 4, 2, 0],
       [3, 7, 8, 4, 0],
       [7, 5, 7, 7, 3],
       [3, 0, 4, 0, 7],
       [8, 9, 1, 4, 8],
       [1, 5, 7, 2, 5],
       [8, 2, 9, 5, 7],
       [7, 5, 5, 9, 2],
       [1, 6, 8, 2, 0],
       [3, 5, 6, 0, 3],
       [8, 2, 0, 4, 6]], dtype=int32)

In [31]:
arr2 = arr.reshape((12,5),order='F')
arr2

array([[3, 8, 6, 5, 7],
       [3, 0, 4, 0, 7],
       [7, 5, 5, 9, 2],
       [6, 6, 4, 2, 0],
       [8, 9, 1, 4, 8],
       [1, 6, 8, 2, 0],
       [3, 7, 8, 4, 0],
       [1, 5, 7, 2, 5],
       [3, 5, 6, 0, 3],
       [7, 5, 7, 7, 3],
       [8, 2, 9, 5, 7],
       [8, 2, 0, 4, 6]], dtype=int32)

In [32]:
arr2 = arr.reshape((4,-1))
arr2

array([[3, 8, 6, 5, 7, 6, 6, 4, 2, 0, 3, 7, 8, 4, 0],
       [7, 5, 7, 7, 3, 3, 0, 4, 0, 7, 8, 9, 1, 4, 8],
       [1, 5, 7, 2, 5, 8, 2, 9, 5, 7, 7, 5, 5, 9, 2],
       [1, 6, 8, 2, 0, 3, 5, 6, 0, 3, 8, 2, 0, 4, 6]], dtype=int32)

In [33]:
arr2 = arr.reshape((-1,10))
arr2

array([[3, 8, 6, 5, 7, 6, 6, 4, 2, 0],
       [3, 7, 8, 4, 0, 7, 5, 7, 7, 3],
       [3, 0, 4, 0, 7, 8, 9, 1, 4, 8],
       [1, 5, 7, 2, 5, 8, 2, 9, 5, 7],
       [7, 5, 5, 9, 2, 1, 6, 8, 2, 0],
       [3, 5, 6, 0, 3, 8, 2, 0, 4, 6]], dtype=int32)

In [34]:
arr1 = np.random.randint(0,10,size = (3,4,5))
arr1.shape

(3, 4, 5)

In [35]:
arr1.T.shape

(5, 4, 3)

In [36]:
arr1 = np.random.randint(0,10,size = (3,4,5))
arr1.shape

(3, 4, 5)

In [37]:
np.transpose(arr1,(1,2,0)).shape

(4, 5, 3)