In [1]:
# 导包
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from IPython.core.interactiveshell import InteractiveShell # 这个对象设置所有行全部输出

# 导入鸢尾花数据集
from sklearn.datasets import load_iris

# 导入数据集划分工具
from sklearn.model_selection import train_test_split

# 导入逻辑回归模型
from sklearn.linear_model import LogisticRegression

# 导入分类模型评估指标accuracy_score
from sklearn.metrics import accuracy_score

# 设置该对象ast_node_interactivity属性的值为all，表示在notebook下每一行有输出的代码全部输出运算结果
InteractiveShell.ast_node_interactivity = "all"

# 解决坐标轴刻度负号乱码
plt.rcParams['axes.unicode_minus'] = False

# 解决中文乱码问题
plt.rcParams['font.sans-serif'] = ['Simhei']
plt.style.use('ggplot')

In [2]:
# 加载数据
iris_data = load_iris()

x = iris_data.data
y = iris_data.target

# 基本的数据探索
x.shape
y.shape

(150, 4)

(150,)

In [3]:
pd.DataFrame(x).head()

pd.DataFrame(y).value_counts()

,0,1,2,3
0,5.1,3.5,1.4,0.2
1,4.9,3.0,1.4,0.2
2,4.7,3.2,1.3,0.2
3,4.6,3.1,1.5,0.2
4,5.0,3.6,1.4,0.2


0
0    50
1    50
2    50
Name: count, dtype: int64

In [5]:
# 数据集划分
Xtrain,Xtest,Ytrain,Ytest = train_test_split(x,y,test_size=0.3,random_state=123)
Xtrain.shape
Ytrain.shape
Xtest.shape
Ytest.shape

(105, 4)

(105,)

(45, 4)

(45,)

In [6]:
# 构建逻辑回归模型
clf = LogisticRegression()

# 模型训练
clf = clf.fit(Xtrain,Ytrain)

In [8]:
# 获取预测结果
y_pred = clf.predict(Xtest)
y_pred,Ytest

(array([1, 2, 2, 1, 0, 1, 1, 0, 0, 1, 2, 0, 1, 2, 2, 2, 0, 0, 1, 0, 0, 1,
        0, 2, 0, 0, 0, 2, 2, 0, 2, 1, 0, 0, 1, 1, 2, 0, 0, 1, 1, 0, 2, 2,
        2]),
 array([1, 2, 2, 1, 0, 2, 1, 0, 0, 1, 2, 0, 1, 2, 2, 2, 0, 0, 1, 0, 0, 2,
        0, 2, 0, 0, 0, 2, 2, 0, 2, 2, 0, 0, 1, 1, 2, 0, 0, 1, 1, 0, 2, 2,
        2]))

In [9]:
# 模型评估
accuracy_score(Ytest,y_pred)

0.9333333333333333

In [10]:
# 获取预测结果的概率分布
clf.predict_proba(Xtest)

array([[1.19935283e-03, 6.34366928e-01, 3.64433719e-01],
       [5.15475592e-05, 1.03708166e-01, 8.96240287e-01],
       [2.26973365e-05, 4.80806079e-02, 9.51896695e-01],
       [3.27307805e-02, 9.22426807e-01, 4.48424121e-02],
       [9.80174919e-01, 1.98250463e-02, 3.48651345e-08],
       [2.57469150e-03, 5.13892979e-01, 4.83532329e-01],
       [4.16769231e-03, 9.08835020e-01, 8.69972873e-02],
       [9.84651386e-01, 1.53485729e-02, 4.11509958e-08],
       [9.74298660e-01, 2.57012386e-02, 1.00926793e-07],
       [1.23894613e-02, 8.95216254e-01, 9.23942843e-02],
       [2.05149438e-04, 1.81239184e-01, 8.18555666e-01],
       [9.80755865e-01, 1.92441096e-02, 2.50560530e-08],
       [5.17425177e-02, 9.01756066e-01, 4.65014163e-02],
       [1.23100900e-04, 1.76090394e-01, 8.23786505e-01],
       [1.24598680e-06, 2.21323201e-02, 9.77866434e-01],
       [1.12365702e-05, 3.25195217e-02, 9.67469242e-01],
       [9.68050496e-01, 3.19494627e-02, 4.13209451e-08],
       [9.88906825e-01, 1.10931

In [11]:
# 查看权重（模型参数）
clf.coef_
clf.intercept_

array([[-0.45799607,  0.82236219, -2.31225851, -0.98187004],
       [ 0.50923947, -0.22371391, -0.18962234, -0.81216269],
       [-0.0512434 , -0.59864828,  2.50188085,  1.79403273]])

array([  9.63653885,   1.77351235, -11.41005119])

In [12]:
# 导包
import torch
import torch.nn.functional as F # 导入神经网络函数库

In [13]:
# 数据准备

n_item = 1000   # 样本容量m
n_feature = 2   # 特征维度n，特征的个数
learning_rate = 0.001   # 学习率，步长
epochs = 100    # 训练轮数

# fake data: 构造假数据
torch.manual_seed(123) # 指定任意随机种子构造随机数
data_x = torch.randn(size=(n_item, n_feature)).float() # 依据随机种子对象生成1000行，2个特征的数据集，取值给定浮点数
data_y = torch.where(torch.subtract(data_x[:, 0]*0.5, data_x[:, 1]*1.5) > 0, 1., 0.).float()
# 这里标签的构建规则是：如果第一个数的0.5倍大于第二个数的0.5倍，则该样本标签取值为1，否则为0

In [15]:
# 借助Pytorch手写逻辑回归算法
class LogisticRegressionManually(object):
    def __init__(self):
        # regression model
        self.w = torch.randn(size=(n_feature, 1), requires_grad=True) # 构造待估参数列向量w
        self.b = torch.zeros(size=(1, 1), requires_grad=True) # 构造偏置b
        # requires_grad为true表示当前这个量是可以求导的，在这里就表示可以进行梯度更新
        # 如果不指定就说明这个量是不能求导更新的
    
    # 定义前向计算，说白了就是构建逻辑回归的决策函数，计算得出标签结果
    def forward(self, x):
        y_hat = F.sigmoid(torch.matmul(self.w.transpose(0, 1), x) + self.b) # 这里其实就是在套用逻辑回归的决策函数w^Tx + b，转置
        return y_hat # 返回预测结果
    
    # 定义损失函数，
    @staticmethod
    def loss_func(y_hat, y):
        return -(torch.log(y_hat)*y + (1-y)*torch.log(1-y_hat)) # 这里其实就是在套用逻辑回归的损失函数，也是手写了一个二分类交叉熵损失函数

    # train，构建训练过程
    def train(self):
        # 100轮训练过程，观察损失函数的下降规律
        for epoch in range(epochs):
            # 1. load data，加载每一条样本数据
            for step in range(n_item):
                # 2. forward calc，前向计算，得出标签预测结果
                y_hat = self.forward(data_x[step])
                y = data_y[step]    # target，在获取当前样本的真实标签结果
                # 3. loss calc，损失函数计算，传入预测值和真实值
                loss = self.loss_func(y_hat, y)
                # 4. backward
                loss.backward() # 反向求导
                # 5. update model(update param)
                with torch.no_grad(): # 更新模型参数
                # 这里为啥要使用with语句，表示在这个上下文环境下不执行梯度更新操作，此时需要完成更新参数
                    self.w.data -= learning_rate * self.w.grad.data # 待估参数列向量w更新
                    self.b.data -= learning_rate * self.b.grad.data # 截距b更新
                self.w.grad.data.zero_() # 记得更新完后归零
                self.b.grad.data.zero_()
            if epoch % 10 == 0:
                print('Epoch: {}, Loss: {}'.format(epoch, loss.item()))


In [16]:
# 执行
if __name__ == '__main__':
    lrm = LogisticRegressionManually()  # 新建模型
    lrm.train()  # 训练

Epoch: 0, Loss: 0.5620617270469666
Epoch: 10, Loss: 0.4762253761291504
Epoch: 20, Loss: 0.43637001514434814
Epoch: 30, Loss: 0.4089241325855255
Epoch: 40, Loss: 0.3875424861907959
Epoch: 50, Loss: 0.3698981702327728
Epoch: 60, Loss: 0.35483989119529724
Epoch: 70, Loss: 0.3416937291622162
Epoch: 80, Loss: 0.33002859354019165
Epoch: 90, Loss: 0.3195469379425049
